SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `ejava` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `ejava` ;

-- -----------------------------------------------------
-- Table `ejava`.`users`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `ejava`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
